#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# file:     bunzip2-r
# autor:    smcicoss [simon@cicoss.net]

# Descomprime todos los ficheros .bz2 que encuentre en el
#   directorio y sus subdirectorios

dir=$(pwd)
echo
echo "ATENCION: va a descomprimir todos los archivos .bz2"
echo -e "que encuentre en el arbol por debajo de \e[0;32m$dir\e[0m"
echo -en "¿quiere continuar?(s/n)"
read r
if [ "$r" == "s" ] || [ "$r" == "S" ]; then
    echo "Descomprimiendo"
    find $dir -iname "*.bz2" -type f -exec bunzip2 {} \;
    echo "Echo"
fi
