#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# empaqueta
# Autor: Simón Martínez
# Categoría: Compresión

# Comprime el directorio que se le pasa
#   como parametro o, en su defecto,
#   los subdirectorios del directrorio actual

dir=$(pwd)

if [ -z "$1" ]; then
    # No se le pasa parametro
    # comprime todos los subdirectorios
    echo -e "\e[0;31mATENCION:\e[0m Se va a proceder al"
    echo " empaquetado y posterior eliminación de todos los"
    echo -e "subdirectorios del directorio actual \e[0;32m$dir\e[0m"
    echo -n "¿quiere continuar?(s/n)"
    read r
    if ! [ "$r" == "s" ] && ! [ "$r" == "S" ]; then
        echo "Cancelado"
        exit 1
    fi

    # obtiene la lista de subdirectorios
    lista=$(find . -maxdepth 1 -type d ! -iname ".")

elif [ -d "$1" ];then
    # Se indica el subdirectorio a comprimir
    echo -e "\e[0;31mATENCION:\e[0m Se va a proceder al"
    echo -e " empaquetado y posterior eliminación de \e[0;32m$1\e[0m"
    echo -n "¿quiere continuar?(s/n)"
    read r
    if ! [ "$r" == "s" ] && ! [ "$r" == "S" ]; then
        echo "Cancelado"
        exit 1
    fi
    lista="$1"

else
    # el parametro pasado no es un directorio
    echo "'$1' no existe o no es un directorio"
    echo "Cancelo"
    exit 2
fi

backIFS=$IFS
IFS=$(printf "\x$(printf %x 10)")

while read -a subdir; do
    # eliminamos posibles barras del final de cada directorio
    temp="$subdir"
    subdir=$(echo "$temp" | sed '/\/$/ s/\/$//g')
    echo -n "empaquetando $subdir"
    destino=${subdir// /_} # substituye espacios por guión bajo en destino
    echo " -> $destino"
    tar -zcvf $destino.tar.gz "$subdir"; # empaqueta con compresión gzip (-z)
    if [ $? == 0 ]; then
        # elimino el origen si no hay error
        echo -e "\e[0;31mEliminando $subdir\e[0m"
        rm -r $subdir;
    else
        # se ha producido un error
        # no se borra y se termina
        echo -e "\e[0;31mError al empaquetar\e[0m $subdir"
        exit 3
    fi
echo -e "\e[0;32mEcho\e[0m"

done <<< $lista
IFS=$backIFS
