#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# file:     gunzip-r
# autor:    smcicoss [simon@cicoss.net]

# Descomprime todos los ficheros .gz (no .tar.gz) 
#   que encuentre en el directorio y sus subdirectorios

dir=$(pwd)
echo
echo "ATENCION: va a descomprimir todos los archivos .gz"
echo -e "que encuentre en el arbol por debajo de \e[0;32m$dir\e[0m"
echo -en "¿quiere continuar?(s/n)"
read r
if [ "$r" == "s" ] || [ "$r" == "S" ]; then
    echo "Descomprimiendo"
    find "$dir" ! -iname "*.tar.gz" -iname "*.gz" -type f -print -exec gunzip -df {} \;
    echo "Echo"
fi
