#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·

# file:     gzip-r
# autor:    smcicoss [simon@cicoss.net]

# Genera un indice del contenido de un archivo .tar o .tar.gz
#   asignandole el mismo_nombre.INDEX

lista=$(find . -maxdepth 1 -type f -iname "*.tar.gz" -or -iname "*.tar")
backIFS=$IFS
IFS=$(echo -en "\n\b")
for file in $lista; do
	nombre="$(basename $file).INDEX"
    echo -e "creando indice \e[0;31m$nombre\e[0m"
    tar -tf $file > "$nombre"
done
IFS=$backIFS
echo -e "\e[0;31mEcho\e[0m"
