#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# file:     un7z-r
# autor:    smcicoss [simon@cicoss.net]

# Descomprime todos los ficheros .7z
#   que encuentre en el directorio y sus subdirectorios

dir=$(pwd)

echo
echo "ATENCION: va a descomprimir todos los archivos .7z"
echo -e "que encuentre en el arbol por debajo de \e[0;32m$dir\e[0m"
echo -en "¿quiere continuar?(s/n)"
read r
if [ "$r" == "s" ] || [ "$r" == "S" ]; then
    echo "Descomprimiendo..."
    #find "$dir" -iname "*.7z" -type f -execdir 7z x {} -o{}- \;
	lista=$(find "$dir" -iname "*.7z" -type f -print)
	for file in $lista; do
		nombre=$(basename "$file" .7z)
		origen=$(dirname "$file")
		destino="$origen/$nombre/"
		echo -e "=============================================\n\n"
		7z x "$file" -o"$destino"
		if [ $? -eq 0 ]; then
			rm -fv "$file"
		fi
	done
    echo "Echo"
fi
