#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# file:     unrar-r
# autor:    smcicoss [simon@cicoss.net]

# Descomprime todos los ficheros .rar 
#   que encuentre en el directorio y sus subdirectorios

dir=$(pwd)

echo
echo "ATENCION: va a descomprimir todos los archivos .rar"
echo -e "que encuentre en el arbol por debajo de \e[0;32m$dir\e[0m"
echo -en "¿quiere continuar?(s/n)"
read r
if [ "$r" == "s" ] || [ "$r" == "S" ]; then
    echo "Descomprimiendo"
    find "$dir" -iname "*.rar" -type f -execdir unrar x {} \;
    echo "Echo"
fi
