#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# file:		desempaqueta
# Autor: 	Simón Martínez

# Extrae el contenido del fichero .tar.gz pasado como parametro
# 	o todos los que encuentre en el direcotrio actual

dir=$(pwd)

if [ -z "$1" ]; then
	# No se ha suministrdo parametro
	echo -e "\e[0;31mATENCION:\e[0m Se va a proceder al"
	echo " desempaquetado y posterior eliminación de todos los"
	echo -e "archivos '*.tar.gz' en el directorio actual \e[0;32m$dir\e[0m"
	echo -n "¿quiere continuar?(s/n)"
	read r
	if ! [ "$r" == "s" ] && ! [ "$r" == "S" ]; then
		echo "Cancelo"
		exit 1
	fi

	lista=$(find . -maxdepth 1 -type f -iname "*.tar.gz")

elif [ -f "$1" ] && [[ "$1" =~ ".tar.gz" ]]; then
	# Se ha suministrado el nombre de un fichero .tat.gz como parametro
	echo -en "\e[0;31mATENCION:\e[0m Se va a proceder al"
	echo -e " desempaquetado y posterior eliminación de \n\t\e[0;32m$1\e[0m"
	echo -n "¿quiere continuar?(s/n)"
	read r
	if ! [ "$r" == "s" ] && ! [ "$r" == "S" ]; then
		echo "Cancelo"
		exit 1
	fi
	lista="$1"
else
	# El fichero pasado como parámetro no existe
	echo "'$1' no existe o no es un '*.tar.gz'"
	echo "Cancelo"
	exit 2
fi

backIFS=$IFS
IFS=$(echo -en "\n\b")

for file in $lista; do
    echo "desempaquetando $file"
    tar -xvzf $file;
    if [ $? == 0 ]; then
		# no se produjo error
		# se borra el fuente
        echo -e "\e[0;31mEliminando $file\e[0m"
        rm -r $file;
    else
		# Hubo error al desempaquetar
		# No se borra el fuente y termina
        echo -e "\e[0;31mError al desempaquetar\e[0m $file"
        exit 3
    fi
done

IFS=$backIFS
echo -e "\e[0;32mEcho\e[0m"
