#! /bin/bash
# -*- ENCODING: UTF-8 -*-

# file:     gzip-r
# autor:    smcicoss [simon@cicoss.net]

# Comprime todos los ficheros(no .gz) 
#   que encuentre en el directorio y sus subdirectorios

dir=${1-"$(pwd)"}
echo
echo "ATENCION: va a comprimir todos los archivos no '.gz''"
echo -e "que encuentre en el arbol por debajo de \e[0;32m$dir\e[0m"
echo -en "¿quiere continuar?(s/n)"
read r
if [ "$r" == "s" ] || [ "$r" == "S" ]; then
    echo "Comprimiendo"
    find "$dir" ! -iname "*.gz" -iname "*" -type f -print -exec gzip -9 {} \;
    echo "Echo"
fi
